- name: enable crond
  become: true
  systemd:
    enabled: true
    daemon_reload: true
    name: crond

- name: enable atd
  become: true
  systemd:
    enabled: true
    daemon_reload: true
    name: atd
