---
- name: full os setup
  hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: include vars
      tags: always
      include_vars:
        dir: vars
    - name: prevent system from suspending during execution (battery)
      tags: always
      command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type nothing
    - name: prevent system from suspending during execution (ac)
      tags: always
      command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing
  tasks:
    - name: import applications role
      tags: 
        - apps
        - roles
      import_role:
        name: applications
    - name: import setup role
      tags: 
        - setup
        - settings
        - roles
      import_role:
        name: setup
    - name: import preferences role
      tags: 
        - preferences
        - prefs
        - roles
      import_role:
        name: preferences
  post_tasks:
    - name: remove 2nd phase cron job
      cron:
        state: absent
        user: root
        name: "fedora setup phase 2"
        cron_file: fedora_setup_2
    - name: restore settings to suspend when inactive (battery)
      tags: always
      command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type suspend
    - name: restore settings to suspend when inactive (ac)
      tags: always
      command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type suspend
