---
- name: reload systemd
  become: true
  systemd:
    daemon_reload: true
- name: reexec systemd
  become: true
  systemd:
    daemon_reexec: true
- name: restart snapd
  become: true
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: snapd
