---
# Clone dotfiles repo ----------------------------------------
- name: setup | dotfiles | clone repo
  ansible.builtin.git:
    repo: "https://github.com/{{ github.dotfiles }}.git"
    dest: "{{ workspace.projects_dir }}/dotfiles"
    clone: true
    update: true
    recursive: true
    track_submodules: true

# Integrate dotfiles ----------------------------------------
- name: setup | dotfiles | integrate user workspace directories 
  block:
    - name: find all workspace directories within dotfiles content
      find:
        path: "{{ workspace.projects_dir }}/dotfiles"
        file_type: directory
        use_regex: true
        recurse: no
        hidden: false
      register: dotfiles_dirs_ws
    - name: symlink workspace directories to user's home
      loop: "{{ dotfiles_dirs_ws.files }}"
      file:
        src: "{{ item.path }}"
        dest: "{{ home }}/{{ item.path | basename }}"
        state: link
        force: true
      when: item.path is directory
    - name: enable nautilus templates
      lineinfile:
        path: "{{ base_dir.config }}/user-dirs.dirs }}"
        state: present
        backup: true
        regexp: XDG_TEMPLATES_DIR
        line: "XDG_TEMPLATES_DIR={{ workspace.templates_dir }}"

- name: setup | dotfiles | integrate runcom directories
  block:
    - name: find all runcom directories within dotfiles content
      find:
        path: "{{ workspace.projects_dir }}/dotfiles"
        file_type: directory
        use_regex: true
        patterns: '^.*\.d$'
        recurse: no
        hidden: true
      register: dotfiles_dirs_runcom
    - name: symlink runcom directories to user's home
      loop: "{{ dotfiles_dirs_runcom.files }}"
      file:
        src: "{{ item.path }}"
        dest: "{{ home }}/{{ item.path | basename }}"
        state: link
        force: true
      when: item.path is directory

- name: setup | dotfiles | integrate runcom files 
  block:
    - name: find all '*.rc' files within dotfiles content
      find:
        path: "{{ workspace.projects_dir }}/dotfiles"
        file_type: file
        use_regex: true
        patterns: '^\.[a-zA-Z0-9\-_]*rc$'
        recurse: no
        hidden: true
      register: dotfiles_files_runcom
    - name: symlink runcom files to user's home
      loop: "{{ dotfiles_files_runcom.files }}"
      file:
        src: "{{ item.path }}"
        dest: "{{ home }}/{{ item.path | basename }}"
        state: link
        force: true
      when: item.path is file
